name: Bug report
description: 'Report an unexpected problem or behavior'
labels: 'P: default'
type: 'bug'
body:
  - type: markdown
    attributes:
      value: |
        [How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)
  - type: dropdown
    id: release
    attributes:
      label: Qubes OS release
      description: Which release(s) of Qubes OS, if any, does this bug affect?
      options:
        - Qubes OS 4.2
        - Qubes OS 4.3
      default: 1
      multiple: true
  - type: textarea
    id: summary
    attributes:
      label: Brief summary
      description: Please briefly describe the problem.
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Please list the steps required to reproduce this bug.
      value: |
        1.
        2.
        3.
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: After performing the steps above, what did you expect to happen?
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: After performing the steps above, what actually happened instead?
  - type: textarea
    id: info
    attributes:
      label: Additional information
      description: Please provide any additional information you believe will help us diagnose and fix this bug.
