name: Close issue with the resolution "not applicable"
on:
  issues:
    types:
      - labeled
jobs:
  add-comment:
    if: "github.event.label.name == 'R: not applicable'"
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This issue has been closed as "not applicable." Here are some common examples of cases in which issues are closed as not applicable:

            - Help and support requests (please see [Help, support, mailing lists, and forum](https://www.qubes-os.org/support/))
            - Questions (please see [Help, support, mailing lists, and forum](https://www.qubes-os.org/support/))
            - Discussion issues (please see [Help, support, mailing lists, and forum](https://www.qubes-os.org/support/))
            - Bug reports for behavior that is already working as intended
            - Enhancement requests to improve things that are already working as intended
            - Issues that rest on mistaken assumptions or misunderstandings
            - Issues that do not provide enough information
            - Issues that are not actionable

            We respect the time and effort you have taken to file this issue, and we understand that this outcome may be unsatisfying. Please accept our sincere apologies and know that we greatly value your participation and membership in the Qubes community.

            Regarding help and support requests, please note that this issue tracker (qubes-issues) is not intended to serve as a help desk or tech support center. Instead, we've set up other [venues where you can ask for help and support, ask questions, and have discussions](https://www.qubes-os.org/support/). By contrast, the issue tracker is more of a technical tool intended to support our developers in their work. We thank you for your understanding.

            If anyone reading this believes that this issue was closed in error or that the resolution of "not applicable" is not accurate, please leave a comment below saying so, and we will review this issue again. For more information, see [How issues get closed](https://www.qubes-os.org/doc/issue-tracking/#how-issues-get-closed).
      - name: Close Issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          close-reason: not_planned
